module.exports = {
  tutorialsSidebar: [
    "tutorials",
    {
      "How To Start": [
        "howtostart/core2-quick-start",
        "howtostart/rosbot---quick-start",
      ],
    },
    {
      "ROS 2 Tutorials": ["ros2-tutorials/rosbot-ros2-demo"],
    },
    {
      "ROS Tutorials": [
        "ros-tutorials/1-ros-introduction",
        "ros-tutorials/2-creating-nodes",
        "ros-tutorials/3-simple-kinematics-for-mobile-robot",
        "ros-tutorials/4-visual-object-recognition",
        "ros-tutorials/5-running-ros-on-multiple-machines",
        "ros-tutorials/6-slam-navigation",
        "ros-tutorials/7-path-planning",
        "ros-tutorials/8-unknown-environment-exploration",
        "ros-tutorials/9-map-navigation",
      ],
    },
    {
      "ROS Projects": [
        "ros-projects/security-guard-robot",
        "ros-projects/control-virtual-robot-from-your-PC",
        "ros-projects/3-using-frontier-exploration",
        "ros-projects/4-object-search",
        "ros-projects/control-robot-by-voice-commands",
      ],
    },
    {
      "ROSbot + ROSDS LIVE-Class": [
        "rosbot-rosds-tutorials/rosbot-rosds-tutorial-1",
      ],
    },
    {
      "ROSbot + AWS RoboMaker": [
        "aws-robomaker/rosbot-aws-robomaker-quick-start",
        "aws-robomaker/run-ros-tutorials-using-aws-robomaker",
        "aws-robomaker/rosbot-aws-robomaker-multiple-machines",
        "aws-robomaker/rosbot-aws-robomaker-example-applications",
      ],
    },
    {
      "ROS Components": [
        "ros-components/ricoh-theta-z1",
      ],
    },
    {
      "Other Tutorials": [
        "other-tutorials/rosbot-rosds-quick-start",
        "other-tutorials/husarnet-cyclone-dds",
        "other-tutorials/rosbot-and-ws2812b-led-signalization"
      ],
    },
    {
      "Mbed Framework": [
        "mbed/1-enviroment-configuration",
      ],
    },
    {
      "Deprecated": [
        "deprecated/hframework-library-development",
        "deprecated/offline-development-tools",
        "deprecated/how-to-use-core2-ros-local-serial-offline",
        "deprecated/using-core2-to-publish-ros-topics-through-usb",
      ],
    },
    // {
    //   type: "autogenerated",
    //   dirName: ".", // generate sidebar slice from the docs folder (or versioned_docs/<version>)
    // },
  ],
};
